config/routes.rb
Rails.application.routes.draw do
  resources :towns
  resources :countries
  root to: 'users#index'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord

end

app/models/town.rb
class Town < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:country_name)
    end
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  before_action :set_town, only: [:show, :edit, :update, :destroy]

  # GET /towns
  # GET /towns.json
  def index
    @towns = Town.all
  end

  # GET /towns/1
  # GET /towns/1.json
  def show
  end

  # GET /towns/new
  def new
    @town = Town.new
  end

  # GET /towns/1/edit
  def edit
  end

  # POST /towns
  # POST /towns.json
  def create
    @town = Town.new(town_params)

    respond_to do |format|
      if @town.save
        format.html { redirect_to @town, notice: 'Town was successfully created.' }
        format.json { render :show, status: :created, location: @town }
      else
        format.html { render :new }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /towns/1
  # PATCH/PUT /towns/1.json
  def update
    respond_to do |format|
      if @town.update(town_params)
        format.html { redirect_to @town, notice: 'Town was successfully updated.' }
        format.json { render :show, status: :ok, location: @town }
      else
        format.html { render :edit }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1
  # DELETE /towns/1.json
  def destroy
    @town.destroy
    respond_to do |format|
      format.html { redirect_to towns_url, notice: 'Town was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_town
      @town = Town.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def town_params
      params.require(:town).permit(:town_name, :country_name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :delete]
  
	helper_method :sort_column, :sort_direction
	
  # GET /users
  # GET /users.json
  def index
    @users = User.order(sort_column + " " + sort_direction)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
		
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name_surname, :photo_link, :phone_number, :country_name, :town_name, :birthday_date, :email, :facebook_link, :other_social_links)
    end
    
    def sort_column
    	User.column_names.include?(params[:sort]) ? params[:sort] : "name_surname"
  	end
  
  	def sort_direction
    	%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  	end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
  	title ||= column.titleize
  	direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  	link_to title, :sort => column, :direction => direction
	end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :country_name %>
    <%= form.text_field :country_name, id: :country_country_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<table>
  <thead>
    <tr>
      <th>Country name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.country_name %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country name:</strong>
  <%= @country.country_name %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Note</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/towns/_form.html.erb
<%= form_with(model: town, local: true) do |form| %>
  <% if town.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(town.errors.count, "error") %> prohibited this town from being saved:</h2>

      <ul>
      <% town.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :town_name %>
    <%= form.text_field :town_name, id: :town_town_name %>
  </div>

  <div class="field">
    <%= form.label :country_name %>
    <%= form.text_field :country_name, id: :town_country_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/towns/edit.html.erb
<h1>Editing Town</h1>

<%= render 'form', town: @town %>

<%= link_to 'Show', @town %> |
<%= link_to 'Back', towns_path %>

app/views/towns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Towns</h1>

<table>
  <thead>
    <tr>
      <th>Town name</th>
      <th>Country name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @towns.each do |town| %>
      <tr>
        <td><%= town.town_name %></td>
        <td><%= town.country_name %></td>
        <td><%= link_to 'Show', town %></td>
        <td><%= link_to 'Edit', edit_town_path(town) %></td>
        <td><%= link_to 'Destroy', town, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Town', new_town_path %>

app/views/towns/new.html.erb
<h1>New Town</h1>

<%= render 'form', town: @town %>

<%= link_to 'Back', towns_path %>

app/views/towns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Town name:</strong>
  <%= @town.town_name %>
</p>

<p>
  <strong>Country name:</strong>
  <%= @town.country_name %>
</p>

<%= link_to 'Edit', edit_town_path(@town) %> |
<%= link_to 'Back', towns_path %>

app/views/users/_form.html.erb
<div class="container-fluid" align="center">
  <div class="panel panel-default panel-table">
    <h1>Notebook</h1>
      <div class="panel-body">

      
        <%= form_with(model: user, local: true) do |form| %>
          <table class="table-striped table-bordered table-list">

            <% if user.errors.any? %>
              <div id="error_explanation">
                <h2>
									<%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:
								</h2>
                <ul>
									<% user.errors.full_messages.each do |message| %>
										<li>
											<%= message %>
										</li>
									<% end %>
                </ul>
              </div>
            <% end %>

						<tbody>
							<div class="field">
								<tr>
									<td>
										<%= form.label :name_surname %>
									</td>
									<td>
										<%= form.text_field :name_surname, id: :user_name_surname %>
									</td>
								</tr>
							</div>

							<div class="field">
								<tr>
									<td>
										<%= form.label :photo_link %>
									</td>
									<td>
										<%= form.text_field :photo_link, id: :user_photo_link %>
									</td>
								</tr>
							</div>

							<div class="field">
								<tr>
									<td>
										<%= form.label :phone_number %>
									</td>
									<td>
										<%= form.text_field :phone_number, id: :user_phone_number %>
									</td>
								</tr>
							</div>

							<div class="field">
								<tr>
									<td>
										<%= form.label :country_name %>
									</td>
									<td>
										<%= form.text_field :country_name, id: :user_country_name %>
									</td>
								</tr>
							</div>

							<div class="field">
								<tr>
									<td>
										<%= form.label :town_name %>
									</td>
									<td>
										<%= form.text_field :town_name, id: :user_town_name %>
									</td>
								</tr>
							</div>

							<div class="field">
								<tr>
									<td>
										<%= form.label :birthday_date %>
									</td>
									<td>
										<%= form.text_field :birthday_date, id: :user_birthday_date %>
									</td>
								</tr>
							</div>

							<div class="field">
								<tr>
									<td>
										<%= form.label :email %>
									</td>
									<td>
										<%= form.text_field :email, id: :user_email %>
									</td>
								</tr>
							</div>

							<div class="field">
								<tr>
									<td>
										<%= form.label :facebook_link %>
									</td>
									<td>
										<%= form.text_field :facebook_link, id: :facebook_link %>
									</td>
								</tr>
							</div>

							<div class="field">
								<tr>
									<td>
										<%= form.label :other_social_links %>
									</td>
									<td>
										<%= form.text_field :other_social_links, id: :user_other_social_links %>
									</td>
								</tr>
							</div>

						</tbody>
					</table>

				<div class="actions">
					<%= form.submit %>
				</div>
			<% end %>

		</div>
	</div>
</div>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="container-fluid">
  	<h1 align="center">Notebook</h1>
    <div class="panel panel-default panel-table">
        <div class="panel-heading">
            <div class="row">
                <div class="col col-xs-6">
                    <h3>Contacts</h3>
                </div>
                <div class="col col-xs-6 text-right">
                    <%= link_to 'Add new contact', new_user_path, class: 'btn btn-primary btn-create' %>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-bordered table-list">
                <thead>
                    <tr>
                        <th>
                            <%= sortable "name_surname", "Name Surname" %>
                        </th>
                        <th>
                            <%= sortable "phone_number", "Phone Number" %>
                        </th>
                        <th>
                            <%= sortable "birthday_date", "Birthday date" %>
                        </th>
                        <th>
                            <%= sortable "email", "Email" %>
                        </th>
                        <th>
                            <%= sortable "facebook_link", "Facebook" %>
                        </th>
                        <th><em class="fa fa-cog"></em></th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                        <tr>
                            <td>
                                <a href="#user_<%= user.id %>" data-toggle="modal" data-target="#user_<%= user.id %>">
                                    <%= user.name_surname %>
                                </a>
                            </td>
                            <td>
                                <%= user.phone_number %>
                            </td>
                            <td>
                                <%= user.birthday_date %>
                            </td>
                            <td>
                                <%= user.email %>
                            </td>
                            <td>
                                <%= user.facebook_link %>
                            </td>
                            <td align="center">
                                <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
                            </td>
                        </tr>

                        <div class="modal fade" id="user_<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="user_<%= user.id %>_label" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" id="user-<%= user.id %>-label">
                                            <%= user.name_surname %>
                                        </h4>
                                    </div>
                                    <div class="modal-body">
                                        Photo link:
                                        <%= user.photo_link %>
                                    </div>
                                    <div class="modal-body">
                                        Phone number:
                                        <%= user.phone_number %>
                                    </div>
                                    <div class="modal-body">
                                        Country:
                                        <%= user.country_name %>
                                    </div>
                                    <div class="modal-body">
                                        Town:
                                        <%= user.town_name %>
                                    </div>
                                    <div class="modal-body">
                                        Birthday date:
                                        <%= user.birthday_date %>
                                    </div>
                                    <div class="modal-body">
                                        Email:
                                        <%= user.email %>
                                    </div>
                                    <div class="modal-body">
                                        Facebook:
                                        <%= user.facebook_link %>
                                    </div>
                                    <div class="modal-body">
                                        Other social link:
                                        <%= user.other_social_links %>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>